Repository MariCornelio/DEV003-burger-queen-api-client, pull requests merged in 2023-04, with the labels that each got.

#43 Updating order summary (cart)
  src/app/interfaces/order.interface.ts
  src/app/menu/menu.component.css
  src/app/menu/menu.component.html
  src/app/menu/menu.component.ts
  src/app/menu/menu.module.ts
  src/app/menu/order/order.component.html
  src/app/menu/order/order.component.ts
  src/app/service/shared-order.service.ts
Labels: priority high, user story 2

#44 Adding security and resetting order
  src/app/app-routing.module.ts
  src/app/guard/auth-fn.guard.ts
  src/app/interfaces/order.interface.ts
  src/app/login/login.component.ts
  src/app/menu/menu.component.html
  src/app/menu/menu.component.ts
  src/app/menu/order/order.component.ts
  src/app/service/shared-order.service.ts
Labels: priority high, user story 2

#49 Updating and adding components
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/delivering/delivered/delivered.component.css
  src/app/delivering/delivered/delivered.component.html
  src/app/delivering/delivered/delivered.component.spec.ts
  src/app/delivering/delivered/delivered.component.ts
  src/app/delivering/delivering-routing.module.ts
  src/app/delivering/delivering.component.css
  src/app/delivering/delivering.component.html
  src/app/delivering/delivering.component.spec.ts
  src/app/delivering/delivering.component.ts
  src/app/delivering/delivering.module.ts
  src/app/interfaces/order.interface.ts
  src/app/kitchen/kitchen.component.css
  src/app/kitchen/kitchen.component.html
  src/app/kitchen/kitchen.component.ts
  src/app/logout-button/logout-button.component.css
  src/app/logout-button/logout-button.component.html
  src/app/logout-button/logout-button.component.spec.ts
  src/app/logout-button/logout-button.component.ts
  src/app/menu/menu.component.html
  src/app/menu/menu.component.ts
  src/app/service/order.service.ts
Labels: user story 2, user story 3, user story 4

#51 Creating Header and editing Kitchen and Delivering
  src/app/delivering/delivered/delivered.component.css
  src/app/delivering/delivered/delivered.component.html
  src/app/delivering/delivered/delivered.component.ts
  src/app/delivering/delivering.component.css
  src/app/delivering/delivering.component.html
  src/app/delivering/delivering.component.ts
  src/app/delivering/delivering.module.ts
  src/app/kitchen/kitchen.component.css
  src/app/kitchen/kitchen.component.html
  src/app/kitchen/kitchen.component.ts
  src/app/login/login.component.ts
  src/app/menu/menu.component.css
  src/app/menu/menu.component.html
  src/app/menu/menu.component.ts
  src/app/menu/order/order.component.ts
  src/app/service/shared-order.service.ts
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.spec.ts
  src/app/shared/header/header.component.ts
  src/app/shared/shared.module.ts
Labels: priority high, user story 3, user story 4
