Repository MariCornelio/DEV003-burger-queen-api-client, pull requests merged in 2023-05, with the labels that each got.

#63 Edit and AddUser button functionality
  src/app/admin/admin.component.html
  src/app/admin/admin.component.ts
  src/app/admin/modal-product/modal-product.component.ts
  src/app/admin/modal-user/modal-user.component.html
  src/app/admin/modal-user/modal-user.component.ts
  src/app/admin/products/products.component.html
  src/app/admin/products/products.component.ts
  src/app/admin/users/users.component.html
  src/app/admin/users/users.component.ts
  src/app/interfaces/products.interface.ts
  src/app/interfaces/users.interface.ts
  src/app/kitchen/kitchen.component.ts
  src/app/login/login.component.ts
  src/app/menu/menu.component.ts
  src/app/service/auth.service.ts
  src/app/service/order.service.ts
  src/app/service/products.service.ts
  src/app/service/shared-admin.service.spec.ts
  src/app/service/shared-admin.service.ts
  src/app/service/shared-order.service.ts
Labels: user story 5, user story 6

#64 Styling HeaderComponent and AdminModule components
  src/app/admin/admin.component.css
  src/app/admin/admin.component.html
  src/app/admin/modal-product/modal-product.component.css
  src/app/admin/modal-product/modal-product.component.html
  src/app/admin/modal-user/modal-user.component.css
  src/app/admin/modal-user/modal-user.component.html
  src/app/admin/products/products.component.css
  src/app/admin/products/products.component.html
  src/app/admin/users/users.component.css
  src/app/admin/users/users.component.html
  src/app/delivering/delivered/delivered.component.css
  src/app/login/login.component.css
  src/app/menu/order/order.component.css
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
  src/app/shared/logout-button/logout-button.component.css
  src/index.html
  src/styles.css
Labels: user story 5, user story 6

#65 Fixing click on the edit buttons of the UserComponent
  src/app/admin/users/users.component.html
Labels: bug, priority high, user story 5

#67 Updating HeaderComponent (adding kitchen button)
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/register/register.component.css
  src/app/register/register.component.html
  src/app/register/register.component.spec.ts
  src/app/register/register.component.ts
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
  src/app/updatepopup/updatepopup.component.css
  src/app/updatepopup/updatepopup.component.html
  src/app/updatepopup/updatepopup.component.spec.ts
  src/app/updatepopup/updatepopup.component.ts
Labels: priority medium, user story 6

#68 Deleting users and products
  src/app/admin/admin.component.css
  src/app/admin/admin.component.html
  src/app/admin/admin.component.ts
  src/app/admin/modal-delete/modal-delete.component.html
  src/app/admin/modal-delete/modal-delete.component.ts
  src/app/admin/modal-user/modal-user.component.ts
  src/app/admin/products/products.component.html
  src/app/admin/products/products.component.ts
  src/app/admin/users/users.component.html
  src/app/admin/users/users.component.ts
  src/app/service/auth.service.ts
  src/app/service/order.service.ts
  src/app/service/products.service.ts
  src/app/service/shared-admin.service.ts
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
Labels: priority high, user story 5, user story 6

#69 Styling the ModalDeleteComponent
  src/app/admin/admin.component.ts
  src/app/admin/modal-delete/modal-delete.component.css
  src/app/admin/modal-delete/modal-delete.component.html
  src/app/admin/modal-delete/modal-delete.component.ts
  src/app/admin/modal-product/modal-product.component.css
  src/app/admin/modal-user/modal-user.component.css
  src/app/kitchen/kitchen.component.ts
  src/app/menu/order/order.component.css
  src/styles.css
Labels: priority medium, user story 5, user story 6

#70 Test
  src/app/login/login.component.spec.ts
  src/app/login/login.component.ts
  src/app/menu/menu.component.spec.ts
  src/app/menu/order/order.component.spec.ts
Labels: priority medium, user story 1, user story 2

#71 Updating Readme and adding assets-readme.
  README.md
  assets-readme/burger-queen-readme.png
  assets-readme/prototipo-de-alta-fidelidad.png
  assets-readme/prototipo-de-baja-fidelidad.png
  assets-readme/resultado-1.png
  assets-readme/resultado-2.png
  assets-readme/resultado-3.png
  assets-readme/resultado-4.png
  assets-readme/resultado-5.png
Labels: priority low, user story 1, user story 2, user story 3, user story 4, user story 5, user story 6

#72 Changing the web service and correcting header
  src/app/service/auth.service.ts
  src/app/service/order.service.ts
  src/app/service/products.service.ts
Labels: user story 1, user story 2, user story 3, user story 4

#73 Enabling loader for login
  src/app/login/login.component.css
  src/app/login/login.component.html
  src/app/login/login.component.ts
  src/assets/spinning-circles.svg
Labels: user story 1

#74 Changing state to loader on errors
  src/app/login/login.component.ts
Labels: bug
